### PR TITLE
Fix sort keys after custom sort all models

### PR DESCRIPTION
**Pull request by lav45**

### CODE REVIEW

**Comment by leandrogehlen** [comment]
Why `branch-alias` into composer.json?
is it really necessary?

**Comment by lav45** [comment]
Yes end. I already explained it in another task https://github.com/kartik-v/yii2-tabs-x/issues/33

**Comment by leandrogehlen** [comment]
Ok.
you removed `"minimum-stability": "dev"`, i think better to use into master branch.

**Comment by lav45** [comment]
The parameter "minimum-stability" needs to be spelled out in the settings composer.json file in the project which connects your package.
You can see how it is configured in packets https://github.com/yiisoft

**Pull request merged**
